### ISSUE TITLE
No device or entities available after successful login

### ISSUE THREAD

**Issue by jchapmantcg** [sebirdman/hass_traeger#54]
## Version of the custom_component
v0.0.8

## Configuration

```yaml

Add your logs here.

```

## Describe the bug
After loading the integration and successfully logging in, it now shows the Traeger app under the integration section but there are no devices or entities available.

## Debug log

```text

2022-11-05 11:48:35 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration traeger which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

```

**Comment by njobrien1006** [comment]
1. Does the Grill appear in the Traeger App?
2. The Warning provided is generated for every CustomComponent installed and doesn't provide any information.
3. Enable debug in configuration.yaml
```
logger:
 #default: warning
 logs: #debug/info/warning/error/critical
   custom_components.hacs: warning
   custom_components.traeger: debug
```
4. Provide more detailed logs.
